- .gitignore
- README.md
- document-avro-schema.js
- document-stream-listener.js
- event.document.sample.json
- package.json
This PR adds a Lambda function/handler (document-stream-listener.js) that listens to a stream of document URIs, then runs on each document URI
```
./jobs/index-resources --uri <document uri>
```
[Updated README](https://github.com/NYPL-discovery/discovery-api-indexer/tree/listen-kinesis-document-queue#local-lambda-development) to test this lambda locally
> Listen kinesis document queue

- README.md
- lib/env-config-helper.js
- lib/resource-indexer.js
- package.json
This PR:
- makes the "outgoing stream" (the stream written to after a doc is indexed) configurable via a new env var "OUTGOING_STREAM_NAME"
- clarifies outgoing *schema* name configuration & documentation
- clarifies NYPL API base url documentation
- adds `standard` as dev dependency, locked at older version known to validate
> Make outgoing stream name configurable

- lib/es-serializer.js
- lib/index.js
- test/bib-serializations-test.js
This PR:
- Makes the indexing of electronic resources consistent between `bib.supplementaryContent` and `item.electronicLocator`
- Ensure electronic items are sorted last (previously sorted by bib shelfmark)
- Fix bug where electronic items acquired bib shelfMark
- Adds formal mapping for item.electronicLocator (previously undefined, which was harmless, but would make filtering difficult if we ever needed to do that)
> Fix inconsistent e-resource indexing

- lib/models/item.js
- package.json
- test/bib-serializations-test.js
- test/item-model-test.js
This PR handles the Indexer side of the catalogItemTypes biz requirements change that allows certain catalogItemTypes > 100 to be flagged as 'Research'. Previously we considered an `itype` as implying 'Research' if the itype was <= 100. The new rule adds new `itype`s > 100 to this classification. Rather than continue hard-coding this increasingly complex check, this PR brings in `nypl-core-objects` to use a new `catalogItemType.collectionType` property to determine the 'Research'-ness of a given `itype`.
Note that the 'Research'-ness of an item does not directly determine whether or not it will be indexed. That is controlled by the `suppressed` flag which is set upstream by the `pcdm-store-updater` based on a number of checks that include checking whether or not it's a 'Research' item. …
> New catalogItemType suppression rule

- .env
- .gitignore
- README.md
- config/event-sources-production.json
- config/event-sources-qa.json
- config/sample.env
- package.json
- test/bib-serializations-test.js
This allows us to keep .env in source control while hiding:
* IAM credentials in ~/.aws dir
* Application runtime vars in ./config/[envname].env
For more information: https://github.com/NYPL/engineering-general/blob/master/standards/node-lambda.md
> Standardize how we deploy to node-lambda

- lib/db.js
This is a long overdue fix to the Indexer to ensure it's checking the
new official predicate identifying the type of records. Previously it
was rdf:type, but as of Winter 2016, new DiscoveryStorePoster
serializations have started using rdfs:type. This change in the Indexer
is necessary to ensure Item & Collection type records are identified.
> Change type check to use rdfs:type instead of rdf:

- README.md
- docs/index-admin.md
Isolate index administration documentation into docs/index-admin with
details about index mapping modification, copying, and new warnings
about the relevancy of the aliasing ("activate" command).
> Add docs/index-admin, cleaner admin docs

- docs/index-admin.md
- lib/index.js
This updates the section in lib/index.js that establishes the baseline
resources index mapping. This is only used when building a brand new
index, but serves secondarily as documentation of the ES schema. Several
new properties have been added lately without updating this mapping.
This commit corrects that as well as cleans it up with fresh
inline documentation.
> Add updated mappings for recently added ES props

- lib/es-serializer.js
- test/bib-serializations-test.js
This changes how the sortable version of the shelfmark is built to
ensure that box/vol/reel numbers occuring mid-string are
'0'-padded. It looks for labels (e.g. box, v., r.) case-insensitively
and ensures differently-cased labels are compared as lowercase (so that
'Box 1' doesn't follow 'box 2', for example). Adds tests.
https://jira.nypl.org/browse/SCC-263
> Change how items are sorted by box/v. in shelfmark

- package.json
Bumps discovery-store-models to v1.2.1, incorporating fix to surface
object_type in Item instances.
https://github.com/NYPL-discovery/discovery-store-models/pull/4
> Bump discovery-store-models to fix item object_type

- lib/es-serializer.js
- lib/index.js
- test/bib-serializations-test.js
- test/data/b11055155.json
Adds 'Contents' and 'Contents title' ES fields.
Note that this entails an updated ES mapping (two additional fields),
which will need to be PUT to update ES mapping.
https://jira.nypl.org/browse/SCC-469
Depends on https://github.com/NYPL/nypl-core/pull/36
> Add Contents fields

- lib/env-config-helper.js
- lib/index.js
- scripts/data/.gitignore
- scripts/identify-ids-by-query.js
- scripts/print-serialized.js
- scripts/write-to-index-document-stream-from-file.js
Adds scripts folder with three new scripts:
- identifiy-ids-by-query: Given an ES query (established inline),
queries the configured ES index and writes identifiers for matching
resources to a CSV
- write-to-index-document-stream-from-file: Counterpart to above, reads
resource identifiers from a CSV and writes them to the specified
IndexDocumentQueue stream (in effect forcing them to be re-indexed.
- print-serialized: Given a bnumber, pulls data from the store,
produces an ES document serialization, and prints it to the console.
Useful for ad hoc verification.
> Adds a few helper scripts for indexing, debugging

- config/development.env
- config/event-sources-development.json
- jobs/index-admin.js
- lib/es-serializer.js
- lib/index.js
- package.json
- test/data/b12082323.json
- test/query-tests/keyword.test.js
Mainly, this adds tests to confirm the new mappings for "Standard Numbers" allow us
to match on items with those identifiers & classifications.
Also does some cleanup things:
- fixes development config to match standards
- fixes config issue in `prepare-query-test-index` missed when QA config added.
- The "mapping-check" admin script has a helpful feature where it suggests a read-made PUT request one can make to fix ES mappings when there are differences between an index mapping and the mapping represented in code. This feature failed to produce anything helpful for "object" types (because object types can contain arbitrary sub-properties, which were not inspected). This PR includes code to suggest a ready-made PUT one can use to push updates to "object" types (with the caveat that the …
> Add standard number tests

- lib/es-serializer.js
- lib/index.js
- lib/utils.js
- test/bib-serializations-test.js
- test/utils.test.js
This branch changes the way we serialize subjects. Wherever we have subjects with sub-subjects delimited by ` -- `, we will know serialize all the sub-subjects separately.
Some questions for the reviewer:
1) Should we be concerned about variable whitespace before/after the  `--`? I am assuming for the moment that this isn't an issue.
2) Is the comment describing the function utils.subtriples readable? Any suggestions for how to improve the clarity of this comment?
3) This function will strip the period from the subjects. Do we want to change this?
4) This PR merges into master. Is that the correct workflow for this repo?
5) Are there any other tests we should add?
> Disaggregate subjects

- config/qa.env
- docs/index-admin.md
Although the index-admin doc describes most of the techniques needed for
copying an index across domains, this update adds specific step-by-step
instructions for the relatively common task of specifically copying
production data down to QA.
The relevant changes can be viewed in rendered form here https://github.com/NYPL-discovery/discovery-api-indexer/blob/fc0d6e39991f76d2d93aa624ee7b56833a093e57/docs/index-admin.md#copying-production-data-to-qa
This also updates the current QA index do the new index I just created while following my own instructions.
> Document copying Production data down to QA

- .travis.yml
- lib/field-mapper.js
- lib/index.js
- lib/resource-indexer.js
- lib/serializers/es-serializer.js
- lib/serializers/resource-holding-serializer.js
- lib/serializers/resource-item-serializer.js
- lib/serializers/resource-serializer.js
- package-lock.json
- package.json
- test/bib-serializations-test.js
- test/data/b11254422.json
This extends the api-indexer to include `Holding` records in the ElasticSearch index for the SCC API. These records are treated in largely the same way that `Item` records are handled, so it is mostly an extension along those principles. This has been tested (in a limited way) locally and verified at least to write the proper objects to the ES index, though more thorough testing will need to be conducted in the QA environment to ensure that this handles everything properly.
The major changes are:
- A refactor of the `serializer` code. With the addition of an additional class it felt like having all of these in a single file was getting unweildy, so I split them out into their own files in a sub-directory. I think this makes these components easier to maintain/understand
- Added the …
> SCC-2207 Add Holding to ElasticSearch index

- .env
- .travis.yml
- config/qa.env
- package-lock.json
AWS will no longer allow deployments of `nodejs6.x` applications via `node-lambda` (travis may have a way around this?) Due to this function cannot be updated as is and needs to be migrated to a more recent node version.
Doing so seems to have no side effects (at least while packages remain pegged to the same versions) but should be looked at carefully to make sure no errors crop up in QA testing
> NOREF Bump nodejs6.10 -> 10.x

- .travis.yml
- lib/serializers/resource-item-serializer.js
- test/bib-serializations-test.js
- test/data/b19834195.json
A minor typo in the `Item` serializer was omitting the new `physicalLocation` and `enumerationChronology` fields due to a missing call to the object. This adds that call and extends one of the test bib records to include these fields, which supports a new unit test.
This also includes a minor update to the travis caching, which was using an old style of reference that seemed to be causing issues for some reason.
> SCC-2271 Add missing statements to ES index

- package.json
This updates the version for discovery-store-models to v1.3.1 to incorporate a fix for how partner items are identified: https://github.com/NYPL-discovery/discovery-store-models/compare/v1.3.0...v1.3.1 . It has already been tested as an alpha release in QA.
> Update discovery-store-models to v1.3.1

- config/sample.env
- lib/platform-api-client.js
- lib/serializers/resource-item-serializer.js
- lib/serializers/resource-serializer.js
- package-lock.json
- package.json
- scripts/print-serialized.js
- test/bib-serializations-test.js
- test/data/b11574666.json
- test/data/b11793485-invalid-856.json
- test/data/b11793485.json
- test/data/platform-endpoint-1acc9199416045c8da801daa3c0cbf5b.json
- test/data/platform-endpoint-3796169b5837a2dd06892b09b735829a.json
- test/data/platform-endpoint-45f0300c32b3b77e51981057855c9c7c.json
This PR is the backend part of Aeon integration, which includes:
* New configuration params to control what item locations are considered Aeon locations, what item shelfmarks (by regex) are considered Aeon shelfmarks, and additional config to authenticate the Bib service.
* When item is identified as an Aeon item, we request the relevant bib from the BibService, parse `856 $u` out of it, and add that URL as a new `aeonUrl` property of the identified items.
* Tests
* Minor update to `print-serialized` script, which aids local ad hoc testing
https://jira.nypl.org/browse/SCC-2666
> SCC-2666 Aeon URLs 

- lib/serializers/resource-serializer.js
- package.json
- test/bib-serializations-test.js
- test/data/hb990049360620203941.json
To make it simpler to separate nypl from partner records, add nyplSoure
to ES doc
https://jira.nypl.org/browse/SCC-2754
> Add nyplSoure to bib serialization

- lib/index.js
- lib/kms-helper.js
- test/bib-serializations-test.js
- test/data/b10011745.json
- test/data/hb990049360620203941.json
Updates tests to confirm that identifiers tagged with type `nypl:Oclc`
are saved to `idOclc`.
This depends on NYPL_CORE_VERSION v1.45a+
https://jira.nypl.org/browse/SCC-2876
Two other housekeeping updates:
1.  Change use of `new Buffer` to `Buffer.from` (former is being deprecated)
2. Adds two bib properties that were manually added to the mapping, but
never added to code. This is just a formality, but could help us recover
should we need to re-create the mapping from code. Properties added:
- nyplSource
- aeonUrl
> SCC-2876 -  Saves oclc identifiers as idOclc

- lib/index.js
Fixes a mistake in an earlier PR, the ElasticSearch type for integers is `integer`, not `int`
> Fix int to integer

- lib/index.js
Fix: Change parallelPublisher to parallelPublisherLiteral so that it
agrees with it's referrent: publisherLiteral. This change has already
been applied to QA and Prod ES indexes. This is just a formality.
Also addresses minor bug in the mapping-check script, causing `object`
type fields to be reported as having different config locally vs remote.
> Fix misnamed parallelPublisherLiteral

- config/test.env
- lib/serializers/resource-item-serializer.js
- test/bib-serializations-test.js
- test/data/b11574666.json
- test/data/b11793485-dev-aeon-base-url.json
- test/data/b11793485-no-aeon-url-in-bib.json
- test/data/b11793485.json
New Aeon linking mechanism draws on two new properties extracted
upstream by discovery-store-poster:
- Bib: aeonURL - The base URL found in the bib 856 $u
- Item: aeonSiteCode - An alphanumeric phrase extracted from item
fieldTag x, which is used in place of the Site= param in the Aeon URL
Depends on NYPL-Core v1.63
https://jira.nypl.org/browse/SCC-3159
> Implement new Aeon linking mechanism

- lib/serializers/resource-serializer.js
- test/bib-serializations-test.js
This code loops through the _items array within the bib serializer. It checks for presence of two different electronicLocator predicates, bf:electronicLocator and nypl:electronicLocator. It creates the property numElectronicResources with the value of the number of statements that have that predicate.
> extract electronic resource count

- lib/serializers/resource-item-serializer.js
- lib/utils.js
- test/utils.test.js
Fixes bug when sorting some range values due to Node's regretable default comparator, which converts elements into strings, leading to this nonsense:
```
> [ 2, 116 ].sort()
[ 116, 2 ]
```
Also general refactoring for DRY
> Fix broken sorting of some range values
